### ISSUE TITLE
"Couldn't read lso file" on `Half Lile 2 Flash`

### ISSUE THREAD

**Issue by adrian17** [ruffle-rs/rust-flash-lso#13]
Game I ran with FP Projector: https://www.newgrounds.com/portal/view/336839

I wasn't able to attach the file so here's a link: http://puu.sh/HQs0l/32bb821cef.sol

Side note: on the `ruffle_changes` branch, I couldn't `cargo run` the `lso-to-json` tool, had to do the following change:

```diff
+d.map(|s| s.1).ok()
-d.ok()
```

**Comment by torokati44** [comment]
Random ping out of nowhere: Can't this be closed now due to #14?
